steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/asp-dotnet-realworld-conduit:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/asp-dotnet-realworld-conduit:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'conduit', '--image', 'gcr.io/$PROJECT_ID/asp-dotnet-realworld-conduit:$COMMIT_SHA', '--region', 'us-east1', '--platform', 'managed', '--allow-unauthenticated', '--max-instances=10']
images:
- 'gcr.io/$PROJECT_ID/asp-dotnet-realworld-conduit:$COMMIT_SHA'
