version: "3.9"
services:
    web:
        build: .
        restart: always
        ports:
            - "8000:80"
        env_file: .env
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            - SA_PASSWORD=${MSSQL_PASSWORD}
            - ACCEPT_EULA="Y"
